// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsMenu.Core")>]
[<assembly: AssemblyProductAttribute("FsMenu")>]
[<assembly: AssemblyDescriptionAttribute("Small DSL to create an interactive cli")>]
[<assembly: AssemblyVersionAttribute("0.0.2")>]
[<assembly: AssemblyFileVersionAttribute("0.0.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsMenu.Core"
    let [<Literal>] AssemblyProduct = "FsMenu"
    let [<Literal>] AssemblyDescription = "Small DSL to create an interactive cli"
    let [<Literal>] AssemblyVersion = "0.0.2"
    let [<Literal>] AssemblyFileVersion = "0.0.2"
